# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'pnpm'
    directory: '/'
    schedule:
      interval: 'monthly'
      day: 'sunday'
    target-branch: 'develop'
    commit-message:
      prefix: 'build'
      include: 'scope'
    groups:
      all-dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'nuxt'
        update-types: ['version-update:semver-major']
      - dependency-name: 'vite'
        update-types: ['version-update:semver-major']
    open-pull-requests-limit: 5 # Avoid Dependabot flooding your PR list
    rebase-strategy: 'auto'
